spring:
  application:
    name: gateway
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://zipkin-server
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
      routes:
          # =====================================
          - id: ms1
            uri: lb://microservice-1
            predicates:
            - Path=/ms1

eureka:
  instance:
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    home-page-url-path: /actuator